--liquibase formatted sql
--changeset NikolaiFufaev:1
--comment first migration


CREATE TABLE favor
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    short_description VARCHAR(255),
    CONSTRAINT pk_favor PRIMARY KEY (id)
);

CREATE TABLE landmark
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    creation_date     date,
    short_description VARCHAR(255)                            NOT NULL,
    type              SMALLINT,
    locality_id       BIGINT,
    CONSTRAINT pk_landmark PRIMARY KEY (id)
);

CREATE TABLE landmark_favor
(
    favor_id    BIGINT NOT NULL,
    landmark_id BIGINT NOT NULL
);

CREATE TABLE locality
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    population BIGINT                                  NOT NULL,
    metro      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_locality PRIMARY KEY (id)
);

ALTER TABLE landmark
    ADD CONSTRAINT uc_landmark_name UNIQUE (name);

ALTER TABLE locality
    ADD CONSTRAINT uc_locality_name UNIQUE (name);

ALTER TABLE landmark
    ADD CONSTRAINT FK_LANDMARK_ON_LOCALITY FOREIGN KEY (locality_id) REFERENCES locality (id);

ALTER TABLE landmark_favor
    ADD CONSTRAINT fk_lanfav_on_favor FOREIGN KEY (favor_id) REFERENCES favor (id);

ALTER TABLE landmark_favor
    ADD CONSTRAINT fk_lanfav_on_landmark FOREIGN KEY (landmark_id) REFERENCES landmark (id);


INSERT INTO locality(name, population, metro)
VALUES ('city 1', 10000, true),
       ('city 2', 1000, false),
       ('city 3', 1000, false),
       ('city 4', 10000, true);



INSERT INTO landmark(name, creation_date, short_description, type, locality_id)
VALUES ('name 1', '1991-10-10', 'short description 1', 1, 1),
       ('name 2', '1991-10-10', 'short description 2', 2, 2),
       ('name 3', '1991-10-10', 'short description 3', 3, 2),
       ('name 4', '1991-10-10', 'short description 4', 0, 3),
       ('name 5', '1991-10-10', 'short description 5', 4, 4);

INSERT INTO favor(name, short_description)
VALUES ('favor 1', 'short description 1'),
       ('favor 2', 'short description 2'),
       ('favor 3', 'short description 3'),
       ('favor 4', 'short description 4');

INSERT INTO landmark_favor
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (2, 2),
       (2, 1),
       (3, 3),
       (3, 2),
       (3, 1),
       (4, 4),
       (4, 1);


--rollback truncate table demo;